data:
  apply_mask: false
  batch_size: 32
  center_slice_keys:
  - pred_truth
  data_dtypes:
    mask: bool
  datadict_indices:
    input:
    - 0
    - 1
  ext: \.dat$
  image_reader:
    kwargs:
      stack_size: 5
      target_shape:
      - 160
      - 160
    type: ImageSlicesMemmap
  loading_order:
  - T1
  - 30Hz
  negate_ind: []
  num_workers: 4
  saving_types:
    mask: SaveJpgNorm
  test: {}
  train:
    dirname: /home/junyi/projects/MRE/Data/Memmap/train_T1_30Hz_50Hz
    shuffle: true
    transforms:
    - type: FlipLR
  valid:
    dirname: /home/junyi/projects/MRE/Data/Memmap/val_T1_30Hz_50Hz
    shuffle: false
    transforms: []
# experiment:
#   best_ckpt_idle_epochs: 10
#   checkpoint: null
#   gpu: 0
#   id: T1_T2_to_50HZstiff
#   logdir: T1_T2_to_50HZstiff/T1_T2_to_50HZstiff_2023-06-07_02-02-16
#   num_epochs: 500
#   print_step: 1
#   save_ckpt_step: 10
#   save_image_step: 1
#   seed: 12501
#   valid_step: 1
# log_formats:
#   l1: .5f
#   l2: .5f
#   lr: .5e
#   psnr: .5f
#   ssim: .5f
#   total_loss: .5f
# losses:
#   l2:
#     input_keys:
#     - pred
#     - pred_truth
#     kwargs: {}
#     type: MSELoss
#     weight: 1.0
# metrics:
#   psnr:
#     input_keys:
#     - pred
#     - pred_truth
#     kwargs: {}
#     type: PSNR
model:
  type: UNet
  kwargs:
    conv: Conv2d
    td: AvgPool2d
    in_channels: 10
    first_channels: 16
    num_trans_down: 5
    branches: 1
    out_channels: 1
    norm:
      type: GroupNorm
      kwargs:
        num_groups: 1
    kernel_size: 3
    padding: 1
    dropout:
      type: Dropout2d
      kwargs:
        p: 0
    max_channels: 512
    split_ebs: 2
# optim:
#   kwargs:
#     lr: 0.0005
#   type: Adam
